### ISSUE TITLE
SignatureDoesNotMatch

### ISSUE THREAD

**Issue by peili** [mirkokiefer/aws-lib#56]
I get the following error message:

"SignatureDoesNotMatch","Message":"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

I already check my Access Key and Secret Key twice. Still the same error. Any idea?

**Comment by bluepuma77** [comment]
I can reproduce this error. It seems it happens when the code is executed within a required file.
```
var aws = require("aws-lib");
var prodAdvOptions = {};
var prodAdv = aws.createProdAdvClient('X', 'Y', 'Z', prodAdvOptions);
var options = { SearchIndex: 'All', Keywords: 'Shirt', ResponseGroup: "Medium" };
prodAdv.call("ItemSearch", options, function(error, result) {
    if (error) {
        console.warn('amazonSearch() - ERROR Amazon API', error);
    } else {
        console.log('amazonSearch() - Amazon result', result);
    }
});
```
This is working for me executed in a plain file. 
But when it's within an express apps' required 'routes' file, then I suddenly get the message "Error: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."

**Comment by bluepuma77** [comment]
I had the same issue with this library, this is a quick fix.

In `lib/aws.js` replace
```
    for(var n in keys) {
      var key = keys[n]
      sorted[key] = query[key]
    }
```
with
```
    for (var i=0; i<keys.length; i++) {
      var key = keys[i];
      sorted[key] = query[key];
    }
```
